apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idswyft-secrets
  namespace: idswyft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: idswyft-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: orkapi/idswyft/secrets
